# Majority Voting Technique

## Importing the libraries

In [22]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [23]:
dataset = pd.read_csv('finalf.csv')
dataset = dataset.drop('Area',1)
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [24]:
X

array([[148.41, 12.63, 470.6, ..., 'Anamalai Series', 24, 750],
       [159.66, 13.96, 513.38, ..., 'Anamalai Series', 27, 705],
       [187.52, 11.35, 672.23, ..., 'Peelamedu Series', 24, 670],
       ...,
       [169.27, 12.9, 546.33, ..., 'Irugur Series', 27, 1555],
       [209.93, 15.88, 607.06, ..., 'Palathurai Series', 26, 1646],
       [186.87, 13.09, 594.4, ..., 'Irugur Series', 29, 998]],
      dtype=object)

In [25]:
y

array(['Banana', 'Banana', 'Banana', ..., 'Coconut', 'Coconut', 'Coconut'],
      dtype=object)

## Encoding categorical data

### Encoding the Independent Variable

In [26]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [5])], remainder='passthrough')
temp=X[:,5]
X = np.array(ct.fit_transform(X))
temp1=X[:,:11]
soiltype={temp[i]:temp1[i] for i in range(len(temp))}

In [27]:
X[0]

array([1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 148.41,
       12.63, 470.6, 0.27, 6.97, 24, 750], dtype=object)

### Encoding the Dependent Variable

In [28]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [29]:
y

array([0, 0, 0, ..., 5, 5, 5])

## Splitting the dataset into the Training set and Test set

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [31]:
print(X_train)

[[0.0 0.0 1.0 ... 7.12 27 1100]
 [0.0 0.0 1.0 ... 7.41 35 513]
 [0.0 0.0 1.0 ... 7.73 27 608]
 ...
 [0.0 0.0 0.0 ... 7.35 28 1285]
 [0.0 0.0 0.0 ... 7.76 32 2828]
 [0.0 1.0 0.0 ... 7.37 26 1682]]


In [32]:
X_test

array([[0.0, 0.0, 0.0, ..., 7.43, 32, 462],
       [0.0, 0.0, 0.0, ..., 7.69, 21, 654],
       [0.0, 0.0, 1.0, ..., 7.53, 32, 401],
       ...,
       [0.0, 0.0, 1.0, ..., 7.15, 28, 632],
       [1.0, 0.0, 0.0, ..., 7.34, 29, 670],
       [0.0, 0.0, 1.0, ..., 7.31, 27, 539]], dtype=object)

In [33]:
y_train

array([ 5, 15,  9, 18,  7, 17,  5, 11, 14,  0,  5,  2, 14, 15,  9, 15,  3,
       11, 18, 13, 10, 11,  3, 12, 15,  7,  8, 15,  8,  5, 14,  0, 16, 15,
       15,  5, 12, 15, 16, 15, 10,  8,  9,  3, 11,  7,  5,  7, 15,  9,  5,
       17, 15, 17,  5,  0,  0, 15, 18,  5, 11, 10,  5,  0, 15, 15,  7,  0,
       19, 15, 18, 18, 15, 13,  5,  0, 15,  7,  0,  5, 14,  5, 18, 15, 15,
        7,  5,  0,  1,  5,  9,  5,  0,  5,  5,  6, 15,  0, 10,  5, 14, 15,
        0,  7,  5,  0,  8,  7,  0,  5,  7,  1,  5,  7, 15, 15,  4, 15, 10,
        2, 15,  3, 11,  7, 11, 13, 18,  3, 19, 15, 10,  7, 15, 15, 16, 15,
        7,  0, 15, 15, 15,  5, 14, 13,  7, 11, 11,  7, 11, 15,  6, 11, 15,
        7,  5,  7, 10, 15, 16, 15, 11, 18, 15, 15, 11, 18, 11, 15,  8,  4,
       15, 11,  5, 15, 11, 11,  5,  1,  5,  7, 15, 16,  6, 13,  0,  7, 14,
       11, 16, 15, 14, 15,  6, 15, 18,  5,  5, 15, 10, 18,  5, 11, 15, 10,
        5, 15,  7,  5,  7,  5, 15,  1,  5, 12, 10, 15,  5,  0,  8,  5, 15,
        5,  9, 15, 15, 15

In [34]:
y_test

array([15, 12, 15, 15,  7,  5, 10,  0, 13, 15,  0, 15, 15,  0, 17, 15, 14,
       11, 15,  5, 11,  7, 15, 18, 15,  5,  1, 15, 10,  0,  5, 15,  2, 12,
       14,  9,  2,  5, 16,  9,  5,  5, 15, 17, 15,  8,  0, 18, 15,  6, 15,
        5,  5,  5, 15,  6, 10, 15, 12,  9,  1,  5, 19,  9,  7, 19,  9,  4,
       17,  0,  5, 19, 15,  0,  5, 13,  1, 15, 10, 15,  2, 15,  5, 10, 15,
       10,  5,  9,  7, 18,  5,  7,  0,  4, 18,  1, 18, 11,  7,  5, 10, 18,
       15,  5,  5, 12, 13, 12,  0,  0,  6, 14,  7, 15, 15,  0,  9, 15,  5,
        7, 12, 11, 10, 16, 15, 15, 14, 16,  5,  5,  0,  5, 15,  6,  7, 12,
        1, 11,  9, 18, 18,  5,  7, 18, 15,  9, 15,  0,  7, 10,  4,  0,  9,
        9, 15, 15, 19,  7, 18,  7,  6,  0,  5,  5, 10,  0, 15,  5, 14,  8,
       12, 11, 11, 15, 15,  0,  0,  4,  0,  0, 12,  6, 15, 10, 16, 12, 17,
       10,  8,  5, 10,  7, 17, 15, 18,  3,  0, 15, 15, 10,  5, 13, 16,  9,
       11,  8, 17,  5,  6, 15,  5,  2,  8, 18,  7, 11,  0, 15, 18, 10, 18,
        5, 17, 10,  5, 15

## Feature Scaling

In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 11:] = sc.fit_transform(X_train[:, 11:])
X_test[:, 11:] = sc.transform(X_test[:, 11:])

In [36]:
X_train

array([[0.0, 0.0, 1.0, ..., -1.277762403572537, -0.2114336004211533,
        0.3461954464933725],
       [0.0, 0.0, 1.0, ..., -0.44051663757759596, 1.723756693088716,
        -0.616769625851324],
       [0.0, 0.0, 1.0, ..., 0.48334075938233967, -0.2114336004211533,
        -0.4609234897819097],
       ...,
       [0.0, 0.0, 0.0, ..., -0.6137398995075851, 0.030465186267580352,
        0.6496852904180214],
       [0.0, 0.0, 0.0, ..., 0.5699523903473317, 0.9980603330225151,
        3.180954637313876],
       [0.0, 1.0, 0.0, ..., -0.5559988121975878, -0.453332387109887,
        1.3009580906238893]], dtype=object)

In [37]:
X_test

array([[0.0, 0.0, 0.0, ..., -0.38277555026760124, 0.9980603330225151,
        -0.7004343936359568],
       [0.0, 0.0, 0.0, ..., 0.36785858476234773, -1.6628263205535554,
        -0.3854611502114565],
       [0.0, 0.0, 1.0, ..., -0.09407011371762009, 0.9980603330225151,
        -0.8005040178489492],
       ...,
       [0.0, 0.0, 1.0, ..., -1.1911507726075423, 0.030465186267580352,
        -0.42155183435384713],
       [1.0, 0.0, 0.0, ..., -0.6426104431625825, 0.27236397295631404,
        -0.35921337992608143],
       [0.0, 0.0, 1.0, ..., -0.7292220741275771, -0.2114336004211533,
        -0.5741169991375895]], dtype=object)

In [38]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
classifier1 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier2 = RandomForestClassifier(n_estimators = 18, criterion = 'entropy', random_state = 0)
classifier3 = KNeighborsClassifier(n_neighbors = 26, metric = 'minkowski', p = 2)
classifier = VotingClassifier(estimators=[('dt',classifier1),('rf',classifier2),('knn',classifier3)],voting='hard',weights=[2,3,1])
classifier.fit(X_train, y_train)

VotingClassifier(estimators=[('dt',
                              DecisionTreeClassifier(criterion='entropy',
                                                     random_state=0)),
                             ('rf',
                              RandomForestClassifier(criterion='entropy',
                                                     n_estimators=18,
                                                     random_state=0)),
                             ('knn', KNeighborsClassifier(n_neighbors=26))],
                 weights=[2, 3, 1])

In [39]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[15 15]
 [12 12]
 [15 15]
 [15 15]
 [ 7  7]
 [ 5  5]
 [15 10]
 [ 0  0]
 [13 13]
 [15 15]
 [ 0  0]
 [15 15]
 [15 15]
 [ 0  0]
 [17 17]
 [15 15]
 [14 14]
 [11 11]
 [15 15]
 [ 5  5]
 [11 11]
 [ 7  7]
 [15 15]
 [18 18]
 [15 15]
 [ 5  5]
 [ 1  1]
 [15 15]
 [11 10]
 [ 0  0]
 [ 5  5]
 [15 15]
 [ 5  2]
 [12 12]
 [14 14]
 [ 0  9]
 [ 2  2]
 [ 5  5]
 [16 16]
 [ 6  9]
 [ 5  5]
 [ 5  5]
 [15 15]
 [17 17]
 [15 15]
 [15  8]
 [ 0  0]
 [18 18]
 [15 15]
 [ 0  6]
 [15 15]
 [ 5  5]
 [ 5  5]
 [ 5  5]
 [15 15]
 [ 6  6]
 [10 10]
 [15 15]
 [12 12]
 [11  9]
 [ 1  1]
 [ 5  5]
 [19 19]
 [ 6  9]
 [ 7  7]
 [19 19]
 [ 9  9]
 [ 4  4]
 [17 17]
 [ 0  0]
 [ 5  5]
 [ 5 19]
 [15 15]
 [ 0  0]
 [ 5  5]
 [13 13]
 [ 1  1]
 [15 15]
 [10 10]
 [15 15]
 [ 2  2]
 [15 15]
 [ 5  5]
 [10 10]
 [15 15]
 [10 10]
 [ 5  5]
 [ 9  9]
 [ 7  7]
 [18 18]
 [ 5  5]
 [ 7  7]
 [ 0  0]
 [ 4  4]
 [18 18]
 [ 1  1]
 [18 18]
 [11 11]
 [ 7  7]
 [ 5  5]
 [ 7 10]
 [18 18]
 [15 15]
 [ 5  5]
 [ 5  5]
 [12 12]
 [13 13]
 [ 7 12]
 [ 0  0]
 [ 0  0]
 [ 6  6]
 

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[23  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 33  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  5  0  0  0  0  0  0  0  0  2  0  0  0  0]
 [ 0  0  0  0  0  0  0 13  0  0  0  0  0  0  0  3  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  4  0  0  0  0  0  0  1  0  0  0  0]
 [ 1  0  0  0  0  0  2  0  0  7  0  1  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0 11  1  0  0  0  3  0  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  0  0  9  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 45  0  0

0.8927038626609443

In [46]:
import serial

def main_func():
    list_values=[]
    list_in_floats=[]
    arduino = serial.Serial('com4', 9600)
    arduino_data = arduino.readline()
    decoded_values = str(arduino_data[0:len(arduino_data)].decode("utf-8"))
    list_values = decoded_values.split(' ')
    for item in list_values:
        list_in_floats.append(float(item))
    arduino_data = 0
    arduino.close()
    return list_in_floats

i=0
sum_ph=0
sum_temp=0
while i<5:
    sensor_value=main_func()
    print(f'Temperature readings from Arduino:',sensor_value[0])
    sum_temp+=sensor_value[0]
    print(f'pH readings from Arduino:',sensor_value[1])
    sum_ph+=sensor_value[1]
    i+=1
avg_temp=int(sum_temp/5)
print(f'Average Temperature:',avg_temp)
avg_ph=round(sum_ph/5,2)
print(f'Average pH:',avg_ph)

Temperature readings from Arduino: 26.0
pH readings from Arduino: 7.25
Temperature readings from Arduino: 26.0
pH readings from Arduino: 7.25
Temperature readings from Arduino: 26.0
pH readings from Arduino: 7.27
Temperature readings from Arduino: 26.0
pH readings from Arduino: 7.44
Temperature readings from Arduino: 26.0
pH readings from Arduino: 7.26
Average Temperature: 26
Average pH: 7.29


In [48]:
l=[]
l1=[]
area=input("Area: ")
soilt=input("Soil type: ")
vals=soiltype[soilt].tolist()
l.extend(vals)
l1.extend(vals)
nval=float(input("N value: "))
l.append(nval)
pval=float(input("P value: "))
l.append(pval)
kval=float(input("K value: "))
l.append(kval)
ec=float(input("EC value: "))
l.append(ec)
print("pH:",avg_ph)
print("Temperature:",avg_temp)
l.append(avg_ph)
l.append(avg_temp)
rainfall=int(input("Rainfall: "))
l.append(rainfall)
temp1=sc.transform([l[11:]]).tolist()
l1.extend(temp1[0])
predicted_value=classifier.predict([l1])
print("Predicted Crop:",le.inverse_transform(predicted_value)[0])

Area: Pogalur
Soil type: Irugur Series
N value: 218.41
P value: 12.63
K value: 470.6
EC value: 0.27
pH: 7.29
Temperature: 26
Rainfall: 1500
Predicted Crop: Coconut


In [43]:
print("Coconut:")
print(le.transform(['Coconut']))

Coconut:
[5]
