# ANN

## Importing the libraries

In [96]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

## Importing the dataset

In [97]:
dataset = pd.read_csv('finalf.csv')
dataset = dataset.drop('Area',1)
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [98]:
X

array([[148.41, 12.63, 470.6, ..., 'Anamalai Series', 24, 750],
       [159.66, 13.96, 513.38, ..., 'Anamalai Series', 27, 705],
       [187.52, 11.35, 672.23, ..., 'Peelamedu Series', 24, 670],
       ...,
       [169.27, 12.9, 546.33, ..., 'Irugur Series', 27, 1555],
       [209.93, 15.88, 607.06, ..., 'Palathurai Series', 26, 1646],
       [186.87, 13.09, 594.4, ..., 'Irugur Series', 29, 998]],
      dtype=object)

In [99]:
y

array(['Banana', 'Banana', 'Banana', ..., 'Coconut', 'Coconut', 'Coconut'],
      dtype=object)

## Encoding categorical data

### Encoding the Independent Variable

In [100]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [5])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [101]:
X[0]

array([1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 148.41,
       12.63, 470.6, 0.27, 6.97, 24, 750], dtype=object)

### Encoding the Dependent Variable

In [102]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y)
y = le.fit_transform(y)

In [103]:
y

array([0, 0, 0, ..., 5, 5, 5])

## Splitting the dataset into the Training set and Test set

In [104]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [105]:
print(X_train)

[[0.0 0.0 0.0 ... 8.15 34 2590]
 [0.0 0.0 0.0 ... 7.96 33 2945]
 [0.0 1.0 0.0 ... 7.37 26 1890]
 ...
 [0.0 0.0 0.0 ... 7.77 31 406]
 [0.0 0.0 1.0 ... 7.2 34 685]
 [0.0 0.0 0.0 ... 7.57 35 478]]


In [106]:
X_test

array([[0.0, 0.0, 0.0, ..., 8.78, 22, 564],
       [0.0, 0.0, 1.0, ..., 7.53, 27, 603],
       [0.0, 1.0, 0.0, ..., 7.88, 20, 468],
       ...,
       [0.0, 0.0, 1.0, ..., 7.64, 35, 596],
       [0.0, 0.0, 1.0, ..., 7.52, 25, 1680],
       [0.0, 0.0, 1.0, ..., 7.35, 30, 1677]], dtype=object)

In [107]:
y_train

array([16, 16,  5, 11,  0, 14, 16, 15,  5, 12,  5,  3,  9,  5, 18, 15,  7,
       15,  1, 15,  6, 15,  5,  3, 15,  0,  0, 16, 15, 18, 15, 18,  6, 15,
       16, 15, 15,  1, 15, 18,  8,  5,  0, 10, 15,  3, 15, 11,  7, 10, 15,
       11, 14,  1, 11, 15,  7, 15,  9,  5, 12,  8,  0,  5,  9, 16,  5,  3,
        5,  5,  7, 15,  7,  5, 10, 15, 12,  7, 15,  7, 10,  5, 13, 18,  9,
       15, 14,  0, 15,  0,  7, 15, 11, 14, 15, 10,  5, 14,  5,  0,  9, 15,
       15, 17, 15, 15, 11,  0,  5, 15,  5, 15,  5, 15,  7, 15,  7, 15,  5,
       16, 11,  5, 16,  7,  5, 15, 12, 13,  5, 12,  5,  4,  7, 17, 17, 14,
       11,  7,  5, 18,  2, 15, 18,  2, 14,  6, 15, 13,  8,  5,  9, 10, 15,
       14,  4, 15, 14,  1, 11,  5, 15,  4, 15, 17, 15,  7, 15, 15, 10, 11,
        6,  0,  1, 15,  0,  2,  7,  4, 15,  0,  5, 15,  7, 15,  7, 13,  0,
        9, 15, 10,  5,  5, 15, 11,  0,  7,  0,  0, 16, 12, 13,  3, 15,  7,
       19,  0,  5,  5,  9, 11, 15,  5,  7, 11,  5,  6,  7, 15, 14,  5,  0,
       14,  5,  0, 19, 10

In [108]:
y_test

array([18, 10,  1, 15,  5,  5,  0,  9, 10, 11, 14,  5,  9,  8,  1, 11,  2,
        0,  0,  5,  0,  5, 11, 18,  4, 10,  5, 14, 15, 15, 18, 15, 15, 18,
       15, 15, 14,  9, 10,  5,  9, 15, 11, 15,  5, 10,  7,  5,  7, 15, 15,
       15,  5,  5, 15, 17,  5, 11,  5,  7, 15, 15, 18, 15, 10,  7, 11, 15,
        9, 15, 10,  5,  8, 14,  0, 17,  5,  8, 19, 13, 15,  5, 15, 15,  5,
        7,  9, 13, 15,  0,  6, 15, 15, 15,  9, 15,  0, 15, 18,  5,  5, 18,
       17, 11,  8,  5,  5,  0,  6, 15,  5,  3, 15,  7,  0,  5, 10,  7, 17,
       15,  5, 15, 12, 18, 15,  5,  8,  7, 15, 10, 18,  0,  5, 15,  0, 13,
       12,  2,  7,  0,  0,  7, 10, 17, 15,  8,  7, 15,  7,  0, 15, 15,  5,
        9, 15, 18, 12,  5, 16,  7,  7,  0, 19, 15, 15,  9,  8, 12, 12, 19,
       18,  0, 10,  9, 18, 14, 17,  0, 15,  7,  9,  9,  9,  7, 15, 15,  0,
       12,  5,  7, 10, 15, 14, 15,  8,  0, 14,  8, 15,  5, 10, 11, 12,  5,
        7, 15,  7,  0,  5, 15, 10,  0, 18,  5, 10, 15,  9, 14, 10,  6, 15,
       15, 18, 11, 15, 11

## Feature Scaling

In [109]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#X_train[:, 11:] = sc.fit_transform(X_train[:, 11:])
#X_test[:, 11:] = sc.transform(X_test[:, 11:])
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)



In [110]:
X_train

array([[-0.18887687, -0.2484236 , -0.82089821, ...,  1.66567403,
         1.47251751,  2.66301785],
       [-0.18887687, -0.2484236 , -0.82089821, ...,  1.12426249,
         1.23539344,  3.22368692],
       [-0.18887687,  4.02538243, -0.82089821, ..., -0.55696282,
        -0.42447506,  1.55747321],
       ...,
       [-0.18887687, -0.2484236 , -0.82089821, ...,  0.58285095,
         0.7611453 , -0.78628144],
       [-0.18887687, -0.2484236 ,  1.21817783, ..., -1.04138367,
         1.47251751, -0.34564293],
       [-0.18887687, -0.2484236 , -0.82089821, ...,  0.01294406,
         1.70964158, -0.67256828]])

In [111]:
X_test

array([[-0.18887687, -0.2484236 , -0.82089821, ...,  3.46088072,
        -1.37297134, -0.53674422],
       [-0.18887687, -0.2484236 ,  1.21817783, ..., -0.10103731,
        -0.18735099, -0.47514959],
       [-0.18887687,  4.02538243, -0.82089821, ...,  0.89629974,
        -1.84721949, -0.68836177],
       ...,
       [-0.18887687, -0.2484236 ,  1.21817783, ...,  0.21241147,
         1.70964158, -0.48620504],
       [-0.18887687, -0.2484236 ,  1.21817783, ..., -0.12953266,
        -0.66159913,  1.22580981],
       [-0.18887687, -0.2484236 ,  1.21817783, ..., -0.61395351,
         0.52402122,  1.22107177]])

In [112]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=20, activation='softmax'))
ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
#import from tf.keras.utils.to_categorical
from tensorflow.keras.utils import to_categorical
y_train=to_categorical(y_train,20)
y_test = to_categorical(y_test,20)


In [122]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)





Epoch 1/100
30/30 [==============================] - 0s 2ms/step - loss: 0.4055 - accuracy: 0.8665
Epoch 2/100
30/30 [==============================] - 0s 2ms/step - loss: 0.4053 - accuracy: 0.8644
Epoch 3/100
30/30 [==============================] - 0s 3ms/step - loss: 0.4042 - accuracy: 0.8676
Epoch 4/100
30/30 [==============================] - 0s 3ms/step - loss: 0.4289 - accuracy: 0.8601
Epoch 5/100
30/30 [==============================] - 0s 3ms/step - loss: 0.4213 - accuracy: 0.8633
Epoch 6/100
30/30 [==============================] - 0s 3ms/step - loss: 0.4157 - accuracy: 0.8687
Epoch 7/100
30/30 [==============================] - 0s 2ms/step - loss: 0.4102 - accuracy: 0.8633
Epoch 8/100
30/30 [==============================] - 0s 3ms/step - loss: 0.4096 - accuracy: 0.8676
Epoch 9/100
30/30 [==============================] - 0s 2ms/step - loss: 0.4078 - accuracy: 0.8654
Epoch 10/100
30/30 [==============================] - 0s 2ms/step - loss: 0.4060 - accuracy: 0.8622
Epoch 11/

30/30 [==============================] - 0s 2ms/step - loss: 0.4003 - accuracy: 0.8590
Epoch 84/100
30/30 [==============================] - 0s 2ms/step - loss: 0.3952 - accuracy: 0.8611
Epoch 85/100
30/30 [==============================] - 0s 3ms/step - loss: 0.3929 - accuracy: 0.8644
Epoch 86/100
30/30 [==============================] - 0s 2ms/step - loss: 0.3907 - accuracy: 0.8665
Epoch 87/100
30/30 [==============================] - 0s 1ms/step - loss: 0.3907 - accuracy: 0.8644
Epoch 88/100
30/30 [==============================] - 0s 1ms/step - loss: 0.3903 - accuracy: 0.8730
Epoch 89/100
30/30 [==============================] - 0s 1ms/step - loss: 0.3897 - accuracy: 0.8654
Epoch 90/100
30/30 [==============================] - 0s 1ms/step - loss: 0.3887 - accuracy: 0.8687
Epoch 91/100
30/30 [==============================] - 0s 1ms/step - loss: 0.3887 - accuracy: 0.8676
Epoch 92/100
30/30 [==============================] - 0s 1ms/step - loss: 0.3891 - accuracy: 0.8665
Epoch 93/100
